name: Linux Build

on:
  push:
    branches:
      - 'main'
      - 'build/*'
    paths-ignore:
      - '**.md'

env:
  FLUTTER_VERSION: 3.10.5

jobs:
  build:
    name: Build and upload Linux binary
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '${{ env.FLUTTER_VERSION }}'

      - name: Install dependencies
        run: |
          apt-get install -y ninja-build
          flutter pub get

      - name: Build Linux package
        run: flutter build linux

      - name: Create AppImage
        run: |
          cp -r build/linux/x64/release/bundle build/linux/AppDir
          cd build/linux

          # Install appimage-builder
          wget -O appimage-builder-x86_64.AppImage https://github.com/AppImageCrafters/appimage-builder/releases/download/v1.1.0/appimage-builder-1.1.0-x86_64.AppImage
          chmod +x appimage-builder-x86_64.AppImage

          ./appimage-builder-x86_64.AppImage --recipe ../../AppImageBuilder.yml --skip-test

          ls -l

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ursa-ds-linux.AppImage
          path: build/linux/URSA Driver Station-latest-x86_64.AppImage
